//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationDocument
    {
        public int ID { get; set; }
        public int PersonnelNumber { get; set; }
        public int Document_number { get; set; }
        public string Education { get; set; }
        public string Specialty { get; set; }
        public string EducationlInstitution { get; set; }
        public System.DateTime DateReceipt { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    
        public virtual Generalinformation Generalinformation { get; set; }
    }
}
