//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generalinformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Generalinformation()
        {
            this.EducationDocuments = new HashSet<EducationDocument>();
            this.Medical_cards = new HashSet<Medical_cards>();
            this.Militaries = new HashSet<Military>();
            this.PassportDocuments = new HashSet<PassportDocument>();
        }
    
        public int ID { get; set; }
        public int Personnel_Number { get; set; }
        public string FIO { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateBirthday { get; set; }
        public int PositionCode { get; set; }
        public System.DateTime DateReceipt { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationDocument> EducationDocuments { get; set; }
        public virtual Positioninformation Positioninformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_cards> Medical_cards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Military> Militaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassportDocument> PassportDocuments { get; set; }
    }
}
