//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Personnel_DepartmentEntities : DbContext
    {
        private static Personnel_DepartmentEntities _context;
        public Personnel_DepartmentEntities()
            : base("name=Personnel_DepartmentEntities")
        {
        }
        public static Personnel_DepartmentEntities GetContext()
        {
            if(_context == null)
            
                _context = new Personnel_DepartmentEntities();
                return _context;
            
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EducationDocument> EducationDocuments { get; set; }
        public virtual DbSet<Generalinformation> Generalinformations { get; set; }
        public virtual DbSet<Medical_cards> Medical_cards { get; set; }
        public virtual DbSet<Military> Militaries { get; set; }
        public virtual DbSet<PassportDocument> PassportDocuments { get; set; }
        public virtual DbSet<Positioninformation> Positioninformations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
