//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassportDocument
    {
        public int ID { get; set; }
        public int PersonnelNumber { get; set; }
        public string NumberSeries { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string IssuedBy { get; set; }
        public string Citizenship { get; set; }
    
        public virtual Generalinformation Generalinformation { get; set; }
    }
}
